server:
  port: 8081
logging:
  level:
    com.lee.yimi.mapper: debug

eureka:
  instance:
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 10 #服务失效时间。默认是90秒，也就是如果Eureka Server在90秒内没有接收到来自Service Provider的Renew操作，就会把Service Provider剔除。
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  profiles:
    active: dev