zuul:
  add-host-header: true
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  prefix: /v1/api
  routes:
    user-server:
      path: /user/**
      strip-prefix: true

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379